preloaded_links = [
    "https://www.youtube.com/watch?v=navXxEZm9vo", # gaming
    "https://www.youtube.com/watch?v=ZGu_risoh3k",
    "https://www.youtube.com/watch?v=WO3gzzSO0Uk", # gaming
    "https://www.youtube.com/watch?v=DisZLXORnNM&ab_channel=AugustTheDuck",
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    "https://www.youtube.com/watch?v=Hwybp38GnZw",
    "https://www.youtube.com/watch?v=tJLTxFOxj4s",
    "https://www.youtube.com/watch?v=2CSqejhO5Wc", # gaming
    "https://www.youtube.com/watch?v=SbV8CRF_duA",
    "https://www.youtube.com/watch?v=M7-h3FO-KKo",
    "https://www.youtube.com/watch?v=kc9crxMzJTk", # gaming
    "https://www.youtube.com/watch?v=fa8k8IQ1_X0",
    "https://www.youtube.com/watch?v=-0j2a2co07Q", # gaming
    "https://www.youtube.com/watch?v=PaFMAgfkpyY", # gaming
    "https://www.youtube.com/watch?v=kYUSfrKFFvk", # gaming
    "https://www.youtube.com/watch?v=C_dNt4UEVZQ",
    "https://www.youtube.com/watch?v=CLE4gCwnbgI", # gaming
    "https://www.youtube.com/watch?v=1U60hVPrHbI",
    "https://www.youtube.com/watch?v=0M4K53XBsjo",
    "https://www.youtube.com/watch?v=XIdQ6gO3AncI",
    "https://www.youtube.com/watch?v=BKX6EhDrgqQ",
    "https://www.youtube.com/watch?v=vkwQzmjw7J8", # gaming
    "https://www.youtube.com/watch?v=oAHbLRjF0vo",
    "https://www.youtube.com/watch?v=mpjBBdGFA-s", # gaming
    "https://www.youtube.com/watch?v=zCy-FuYaj1s",
    "https://www.youtube.com/watch?v=ZfuRKLI9mSc",
    "https://www.youtube.com/watch?v=EQP-lfVRgX8&t=54s",
    "https://www.youtube.com/watch?v=xmlQN57rA5k", # gaming
    "https://www.youtube.com/watch?v=88vmzn_LufA",
    "https://www.youtube.com/watch?v=vuvckBQ1bME",
    "https://www.youtube.com/watch?v=VQY_m3wCBCE", # gaming
    "https://www.youtube.com/watch?v=o5hTiKwH4-g",
    # "https://www.youtube.com/watch?v=T_j86uJWyyk",
    "https://www.youtube.com/watch?v=PvzhE_MuMhM",
    "https://www.youtube.com/watch?v=rl_3wguVLsk",
    "https://www.youtube.com/watch?v=UIFIZ5V_o2I",
    # "https://www.youtube.com/watch?v=K2RP1m_--ys",
    "https://www.youtube.com/watch?v=w0acyYZAfio",
    "https://www.youtube.com/watch?v=-JIpItvRfv4",
    "https://www.youtube.com/watch?v=VRPuHKRtZDE",
    "https://www.youtube.com/watch?v=P5qUiTBocm4",
    "https://www.youtube.com/watch?v=tj6ot2HVEmQ",
    "https://www.youtube.com/watch?v=j8DxdibHibU",
    "https://www.youtube.com/watch?v=YhoFR48tU48",
    "https://www.youtube.com/watch?v=viWHdRx9C34",
    "https://www.youtube.com/watch?v=vC5cHjcgt5g",
    "https://www.youtube.com/watch?v=aApSteSbeGA",
    "https://www.youtube.com/watch?v=W_VV2Fx32_Y"
]